version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.evaluation
    volumes:
      - app_data:/app/data
      - uploads_data:/app/uploads
    restart: unless-stopped

volumes:
  app_data:
  uploads_data:
